### Importação de dados

In [ ]:
import pandas as pd
carros_df = pd.read_csv(r"auto.csv", sep = ";", encoding="latin1")
clientes_df = pd.read_csv(r"clientes1.csv", sep = ";", encoding="latin1")
carros_df  = carros_df.rename(columns={"ï»¿auto_id":"auto_id","id_cliente":"id_client"})
display(clientes_df)
display(carros_df)

,id_client,age,monthly_income,city,state,gender,education_level
0,1001,50,14544,Muriaé,MG,NaN,NaN
1,1002,31,1230,Araxá,MG,male,NaN
2,1003,51,2428,Jaú,SP,male,NaN
3,1004,51,20223,Veranópolis,RS,male,NaN
4,1005,25,19924,São Paulo,SP,male,NaN
...,...,...,...,...,...,...,...
35014,36028,34,9286,Carpina,PE,male,Da 5ª à 8ª série do ensino fundamental (antigo...
35015,36029,24,8396,Petrópolis,RJ,male,Ensino médio incompleto (antigo 2º grau
35016,36030,37,4832,Recife,PE,male,Ensino médio completo (antigo 2º grau
35017,36031,50,20698,Santana de Parnaíba,SP,male,4ª série completa do ensino fundamental (antig...
35018,36032,51,7526,Itapetininga,SP,male,Educação superior completa

,auto_id,auto_brand,auto_model,auto_year,auto_value,id_client
0,1993Au16811,Audi,100 2.8 V6,1993,40000,28596
1,1994Au13275,Audi,100 2.8 V6 Avant,1994,13873,1048
2,1998Pe10697,Peugeot,106 Passion 1.0 3p,1998,7000,34309
3,1999Pe13343,Peugeot,106 Passion 1.0 3p,1999,8000,14743
4,2000Pe13776,Peugeot,106 Passion 1.0 3p,2000,6000,31750
...,...,...,...,...,...,...
35024,2011Fi11771,Fiat,Palio,2011,24168,11300
35025,2011Fi11772,Fiat,Uno,2011,26912,20017
35026,2011Fi11773,Fiat,Marea,2011,"32392,7",17697
35027,2011Fi11774,Fiat,Uno,2011,"37873,4",9006
35028,2011Fi11775,Fiat,Palio,2011,"43354,1",10524

### 2) Qual a média salarial dos clientes para cada estado do sudeste?

In [ ]:
clientes_estados_sudoeste= clientes_df.loc[clientes_df["state"].isin(["SP", "RJ", "MG", "ES"])]
media_estado = clientes_estados_sudoeste.groupby("state").mean()
media_estado = media_estado[["monthly_income"]]
def formatar(valor):
    return f"${valor:,.2f}"
media_estado["monthly_income"] = media_estado["monthly_income"].map(formatar)
display(media_estado)

      monthly_income
state
ES        $11,867.91
MG        $11,498.02
RJ        $11,462.05
SP        $11,577.04

### 3) Qual o maior salário? E o menor?

In [112]:
estado_salario = clientes_estados_sudoeste[["state", "monthly_income"]]
estado_salario = estado_salario.groupby("state").agg(['max', 'min'])
# estado_salario = clientes_df[["state", "monthly_income"]]
# estado_salario = estado_salario.groupby("state").agg(['min', 'max'])
display(estado_salario)

      monthly_income
                 max   min
state
ES             21938  1042
MG             22141  1025
RJ             40000  1028
SP             29300  1000

### 4) Qual o percentual de clientes acima de 60 anos? (Responda com precisão de duas casas decimais)

In [113]:
clientes_acima60 = estados_sudoeste.loc[clientes_df["age"] > 60, :]
total_clientes = clientes_df
print("O total de clientes acima de 60 anos é {:.2%} ".format(len(clientes_acima60) / len(total_clientes)))

O total de clientes acima de 60 anos é 2.70%

### 5) Relacione as cidades dos clientes com seus carros. Qual cidade possui mais carros da marca Ford?

In [114]:
# cidade_carro = pd.merge(clientes_df[["id_client", "city"]], carros_df[["id_client","auto_brand"]], on="id_client")
# cidade_carro = cidade_carro.loc[cidade_carro["auto_brand"] == "Ford", :]
# cidade_carro = cidade_carro.groupby("city").sum()
# display(cidade_carro)
cliente_carro_df = pd.merge(clientes_estados_sudoeste[["id_client", "city"]], carros_df[["id_client","auto_brand"]], on="id_client")
qtd_carro_marca_cidade = cliente_carro_df.loc[cidade_carro["auto_brand"] == "Ford", :]
qtd_carro_marca_cidade = cidade_carro.groupby("city")[["auto_brand"]].nunique()
top1_carro_marca_ford = qtd_carro_marca_cidade["auto_brand"].sort_values(ascending=False).reset_index()
display(top1_carro_marca_ford.head(1))

        city  auto_brand
0  São Paulo          36

### 6) Quantas cidades distintas existem dentre os clientes do RS e quais são elas?

In [138]:
from unidecode import unidecode

clientes_rs = clientes_df[["state", "city"]].loc[clientes_df["state"] == "RS",:]


def formatar(text):
    text = text.strip()
    text = unidecode(text) # Remove acentuação
    text = text.lower() # deixa tudo minúsculo
    return text

clientes_rs["city"] = clientes_rs["city"].astype(str)
clientes_rs["city"] = clientes_rs["city"].apply(formatar) 
pd.set_option("display.max_rows", None) 
qtd_cidades_rs = cidades_rs.groupby("state").nunique()
display(qtd_cidades_rs)
display(cidades_rs)

       city
state
RS      216

      state                       city
3        RS                veranopolis
50       RS               porto alegre
89       RS              caxias do sul
92       RS                       bage
156      RS                   gravatai
202      RS               sao leopoldo
367      RS                dois irmaos
376      RS                     viamao
391      RS                     canoas
393      RS                    cangucu
478      RS                 rio grande
484      RS             lagoa vermelha
534      RS            sapucaia do sul
544      RS                 sobradinho
552      RS                     esteio
577      RS                 santa rosa
605      RS                passo fundo
618      RS              novo hamburgo
632      RS            salvador do sul
643      RS            bento goncalves
659      RS               cachoeirinha
668      RS            eldorado do sul
688      RS                    sinimbu
749      RS                     torres
804      RS                   alvorada
807      RS            palmares do sul
840      RS                     sertao
865      RS                    triunfo
972      RS                    camaqua
1008     RS                santa maria
1057     RS                    pelotas
1103     RS                farroupilha
1113     RS                charqueadas
1181     RS                  cruz alta
1351     RS                      girua
1362     RS                    taquara
1369     RS                    panambi
1466     RS                    gramado
1639     RS                  garibaldi
1689     RS                     tapera
1737     RS                      marau
1808     RS                     guaiba
1918     RS             estancia velha
1943     RS  santo antonio da patrulha
2081     RS                      tapes
2120     RS          santa cruz do sul
2160     RS                    guapore
2414     RS       frederico westphalen
2604     RS              victor graeff
2612     RS                 nova araca
2912     RS             capao da canoa
2933     RS                   jaguarao
2934     RS           cachoeira do sul
2989     RS                     itaara
3207     RS                    lajeado
3320     RS      santana do livramento
3400     RS                    erechim
3420     RS     sao miguel das missoes
3595     RS           balneario pinhal
3650     RS            flores da cunha
3664     RS                 nova hartz
3817     RS                       ijui
3833     RS               vista gaucha
3908     RS                 uruguaiana
3966     RS                       joia
3983     RS                  carazinho
4048     RS                   soledade
4112     RS                    vacaria
4359     RS                sao nicolau
4595     RS              antonio prado
4655     RS          capela de santana
4810     RS                dom pedrito
4882     RS  santo antonio do planalto
5048     RS                  tramandai
5057     RS              restinga seca
5255     RS            tenente portela
5405     RS         sao pedro da serra
5600     RS                    estrela
5609     RS                    rolante
5679     RS             salto do jacui
5691     RS                    ararica
5748     RS                 sao marcos
5777     RS          boqueirao do leao
5876     RS            nova santa rita
5930     RS                constantina
5998     RS                        nan
6052     RS        boa vista do burica
6075     RS             venancio aires
6265     RS                    colinas
6288     RS                      feliz
6305     RS                     canela
6319     RS                 ronda alta
6326     RS                  muliterno
6382     RS                        poa
6405     RS               tres de maio
6542     RS                      agudo
6707     RS                     osorio
6718     RS       palmeira das missoes
6814     RS          barao de cotegipe
6917     RS                  sao borja
7533     RS                   alegrete
7578     RS                horizontina
7994     RS                  xangri-la
8013     RS         boa vista do incra
8079     RS         julio de castilhos
8128     RS                 candelaria
8192     RS                     portao
8308     RS                    cacequi
8337     RS                  rio pardo
8403     RS                   ilopolis
8737     RS                     nonoai
8801     RS                    camargo
8820     RS                 palmitinho
9155     RS                 montenegro
9212     RS                    sarandi
9939     RS                tres coroas
9982     RS             carlos barbosa
10239    RS                sao gabriel
10328    RS                    coxilha
10378    RS                     itaqui
10559    RS                     seberi
10583    RS             cambara do sul
10819    RS                  sapiranga
11004    RS                 vale verde
11068    RS               nao-me-toque
11137    RS                  igrejinha
11301    RS                 crissiumal
11336    RS                     quarai
11501    RS                   santiago
11630    RS                      ivoti
11667    RS               nova bassano
11710    RS               santo angelo
12284    RS       sao sebastiao do cai
12643    RS                  redentora
12863    RS                    cerrito
13140    RS              barros cassal
13372    RS      nova esperanca do sul
13380    RS                cerro largo
13493    RS                   tio hugo
13496    RS                   londrina
13889    RS          bom retiro do sul
14165    RS                  vera cruz
14229    RS                  unistalda
14347    RS            lindolfo collor
14521    RS              bom principio
14968    RS                   teutonia
15005    RS                   candiota
15347    RS    santa vitoria do palmar
15474    RS            cacapava do sul
15751    RS     sao francisco de assis
15911    RS                 nova prata
16514    RS                    taquari
16543    RS       santa barbara do sul
16769    RS                     parobe
16818    RS            nova candelaria
16869    RS                   tapejara
17071    RS                  campo bom
17171    RS                    ibarama
17399    RS                 roca sales
17436    RS            sao jose do sul
18035    RS            trindade do sul
18861    RS                    tupandi
18890    RS         faxinal do soturno
19055    RS              lavras do sul
19096    RS                picada cafe
19543    RS     sao francisco de paula
19612    RS                   sao sepe
19805    RS              minas do leao
20000    RS               sao jeronimo
20079    RS               cerro branco
20445    RS           sao luiz gonzaga
20878    RS              fazenda souza
20926    RS             arroio do meio
20950    RS                    ibiruba
21360    RS                tupancireta
21411    RS                    ciriaco
21415    RS                  tucunduva
21561    RS                   piratini
21924    RS              arroio grande
22120    RS              candido godoi
22570    RS              arroio do sal
22599    RS        sao lourenco do sul
23955    RS               manoel viana
23963    RS                      casca
24030    RS      sao jose do hortencio
24309    RS                  ernestina
24839    RS             rosario do sul
25041    RS                   viadutos
25344    RS                  vila seca
25447    RS              porto  alegre
25454    RS        encruzilhada do sul
25510    RS  santo antonio das missoes
25705    RS           pinheiro machado
25716    RS           barra do ribeiro
25820    RS          sao jose do norte
26248    RS             paraiso do sul
26265    RS                    quintao
27013    RS             sertao santana
27231    RS            arroio do padre
28302    RS            itorresgrejinha
28654    RS                      parai
28866    RS                  encantado
28894    RS            tres cachoeiras
29356    RS                      butia
29402    RS              bom progresso
29514    RS                     ibiaca
30197    RS                    alecrim
31533    RS                   cidreira
31547    RS             terra de areia
32186    RS                 jaboticaba
32997    RS                    selbach
33220    RS                 erval seco
33889    RS             coronel bicaco
34010    RS               campo bom rs
34023    RS         sao joao da urtiga
34141    RS                 porto maua